[package]
name = "twitter-collection-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.28.0", features = ["bundled"] }
futures = "0.3.25"
egg-mode = "0.16.0"
mime = "0.3.16"
tokio = { version = "1.24.1", features = ["full"] }
redis = "0.22.2"
time = { version = "0.3.17", features = ["macros"] }

[[bin]]
name = "app"
path = "src/main.rs"
